# ==========================
# 389. Find the Difference
# ==========================
# Difficulty: Easy
#
# You are given two strings `s` and `t`.
#
# String `t` is generated by random shuffling string `s` and then add one more letter at a random position.
#
# Return the letter that was added to `t`.
#
#  
#
# **Example 1:**
#
# **Input:** s = &quot;abcd&quot;, t = &quot;abcde&quot;
# **Output:** &quot;e&quot;
# **Explanation:** &#39;e&#39; is the letter that was added.
#
# ```
#
# **Example 2:**
#
# **Input:** s = &quot;&quot;, t = &quot;y&quot;
# **Output:** &quot;y&quot;
#
# ```
#
#  
#
# **Constraints:**
#
# 	
# - `0 &lt;= s.length &lt;= 1000`
# 	
# - `t.length == s.length + 1`
# 	
# - `s` and `t` consist of lowercase English letters.
#
# ====== SOLUTION ======

class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        r=0
        for i in s:
            r^=ord(i)
        for i in t:
            r^=ord(i)
        return chr(r)
